#!/bin/bash
# =============================================================================
# setup.sh — Matrix Synapse + Element Web + Jitsi + Nginx Stack Configurator
# =============================================================================
# Run this inside the LXC after first boot to configure your stack.
#
# Usage:
#   ./setup.sh --domain chat.example.com [OPTIONS]
#
# Options:
#   --domain <domain>       Required. Base domain (Element served here)
#   --admin-user <user>     Matrix admin username          (default: admin)
#   --admin-pass <pass>     Matrix admin password          (auto-generated)
#   --postgres-pass <pass>  PostgreSQL synapse DB password (auto-generated)
#   --valkey-pass <pass>    Valkey cache password          (auto-generated)
#   --jitsi-pass <pass>     Jitsi internal XMPP password   (auto-generated)
#   --turn-secret <secret>  coturn TURN shared secret      (auto-generated)
#   --skip-ssl              Use self-signed certs instead of Let's Encrypt
#   --staging               Use Let's Encrypt staging (testing only)
#   --reconfigure           Re-run config without reinstalling (update domain etc)
#   --help                  Show this help
#
# What gets configured:
#   chat.example.com        → Element Web (Nginx HTTPS)
#   matrix.chat.example.com → Matrix Synapse homeserver (Nginx HTTPS)
#   meet.chat.example.com   → Jitsi Meet (Nginx HTTPS, widget-only by design)
#
# Security note:
#   meet.<domain> is NOT publicly linked from Element — accessible only as an
#   Element widget. Nginx restricts direct browsing to the Jitsi URL.
# =============================================================================

set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colour output ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()   { echo -e "${YELLOW}[!]${NC} $*"; }
error()  { echo -e "${RED}[✗]${NC} $*" >&2; }
info()   { echo -e "${BLUE}[→]${NC} $*"; }
header() {
  echo ""
  echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
  echo -e "${CYAN}${BOLD}  $*${NC}"
  echo -e "${BLUE}${BOLD}══════════════════════════════════════════════════${NC}"
}

gen_pass() { openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 40; }
gen_hex()  { openssl rand -hex 32; }

# ── Defaults ──────────────────────────────────────────────────────────────────
DOMAIN=""
ADMIN_USER="admin"
ADMIN_PASS=""
POSTGRES_PASS=""
VALKEY_PASS=""
JITSI_PASS=""
TURN_SECRET=""
SKIP_SSL=false
STAGING=false
RECONFIGURE=false

# ── Arg parsing ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)        DOMAIN="$2";        shift 2 ;;
    --admin-user)    ADMIN_USER="$2";    shift 2 ;;
    --admin-pass)    ADMIN_PASS="$2";    shift 2 ;;
    --postgres-pass) POSTGRES_PASS="$2"; shift 2 ;;
    --valkey-pass)   VALKEY_PASS="$2";   shift 2 ;;
    --jitsi-pass)    JITSI_PASS="$2";    shift 2 ;;
    --turn-secret)   TURN_SECRET="$2";   shift 2 ;;
    --skip-ssl)      SKIP_SSL=true;      shift   ;;
    --staging)       STAGING=true;       shift   ;;
    --reconfigure)   RECONFIGURE=true;   shift   ;;
    --help|-h)
      head -40 "$0" | grep '^#' | sed 's/^# \{0,2\}//'
      exit 0
      ;;
    *) error "Unknown option: $1 (use --help)"; exit 1 ;;
  esac
done

# ── Validate ──────────────────────────────────────────────────────────────────
[[ -z "$DOMAIN" ]] && { error "Required: --domain chat.example.com"; exit 1; }
[[ $EUID -ne 0 ]]  && { error "Must run as root inside the LXC"; exit 1; }

# Validate packages are present (build phase must have run)
for cmd in nginx psql valkey-server python3 jicofo; do
  command -v "$cmd" &>/dev/null || \
    systemctl list-unit-files | grep -q "^${cmd%%-*}" || true
done

# ── Generate missing secrets ──────────────────────────────────────────────────
[[ -z "$ADMIN_PASS"    ]] && ADMIN_PASS="$(gen_pass)"
[[ -z "$POSTGRES_PASS" ]] && POSTGRES_PASS="$(gen_pass)"
[[ -z "$VALKEY_PASS"   ]] && VALKEY_PASS="$(gen_pass)"
[[ -z "$JITSI_PASS"    ]] && JITSI_PASS="$(gen_pass)"
[[ -z "$TURN_SECRET"   ]] && TURN_SECRET="$(gen_hex)"

MATRIX_SHARED_SECRET="$(gen_hex)"
JITSI_APP_SECRET="$(gen_pass)"
LXC_IP=$(hostname -I | awk '{print $1}')

# ── Computed sub-domains ──────────────────────────────────────────────────────
MATRIX_DOMAIN="matrix.${DOMAIN}"
JITSI_DOMAIN="meet.${DOMAIN}"
ELEMENT_DOMAIN="${DOMAIN}"

# ── Save environment (chmod 600 - secrets protected) ─────────────────────────
ENV_FILE="/root/.matrix-stack.env"
cat > "${ENV_FILE}" <<EOF
# Matrix Stack Configuration - generated by setup.sh
# DO NOT share this file - contains secrets
DOMAIN=${DOMAIN}
MATRIX_DOMAIN=${MATRIX_DOMAIN}
JITSI_DOMAIN=${JITSI_DOMAIN}
ELEMENT_DOMAIN=${ELEMENT_DOMAIN}
LXC_IP=${LXC_IP}
ADMIN_USER=${ADMIN_USER}
ADMIN_PASS=${ADMIN_PASS}
POSTGRES_PASS=${POSTGRES_PASS}
VALKEY_PASS=${VALKEY_PASS}
JITSI_PASS=${JITSI_PASS}
TURN_SECRET=${TURN_SECRET}
MATRIX_SHARED_SECRET=${MATRIX_SHARED_SECRET}
JITSI_APP_SECRET=${JITSI_APP_SECRET}
SKIP_SSL=${SKIP_SSL}
STAGING=${STAGING}
SETUP_DIR=${SETUP_DIR}
SETUP_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
chmod 600 "${ENV_FILE}"

# Export everything for child scripts
set -a
source "${ENV_FILE}"
set +a

# ── Banner ────────────────────────────────────────────────────────────────────
clear
echo ""
echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════════════════════╗"
echo "  ║   Matrix Synapse + Element Web + Jitsi Stack Setup  ║"
echo "  ╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "  ${BOLD}Domain:${NC}       ${DOMAIN}"
echo -e "  ${BOLD}Element Web:${NC}  https://${ELEMENT_DOMAIN}"
echo -e "  ${BOLD}Matrix API:${NC}   https://${MATRIX_DOMAIN}"
echo -e "  ${BOLD}Jitsi Meet:${NC}   https://${JITSI_DOMAIN}  (widget-only)"
echo -e "  ${BOLD}LXC IP:${NC}       ${LXC_IP}"
echo -e "  ${BOLD}SSL:${NC}          $([[ $SKIP_SSL == true ]] && echo 'Self-signed' || echo "Let's Encrypt$([[ $STAGING == true ]] && echo ' (staging)' || echo '')")"
echo ""
echo -e "  ${YELLOW}Credentials saved to:${NC} ${ENV_FILE}"
echo ""

# ── Run setup sub-scripts in order ───────────────────────────────────────────
SETUP_SCRIPTS_DIR="${SETUP_DIR}/setup"
if [[ ! -d "${SETUP_SCRIPTS_DIR}" ]]; then
  error "Setup scripts not found at ${SETUP_SCRIPTS_DIR}"
  error "Ensure the full repo is present at ${SETUP_DIR}"
  exit 1
fi

SETUP_SCRIPTS=$(ls -1 "${SETUP_SCRIPTS_DIR}/" | grep '^[0-9][0-9]-' | sort)

for script in ${SETUP_SCRIPTS}; do
  header "$(echo $script | sed 's/\.sh$//' | sed 's/^[0-9]*-//')"
  chmod +x "${SETUP_SCRIPTS_DIR}/${script}"
  bash "${SETUP_SCRIPTS_DIR}/${script}"
  EXIT_STATUS=$?
  if [[ $EXIT_STATUS -ne 0 ]]; then
    error "Setup step '${script}' failed (exit ${EXIT_STATUS})."
    error "Check the output above. You can re-run setup.sh safely."
    exit 1
  fi
  log "${script} complete"
done

# ── Final summary ─────────────────────────────────────────────────────────────
header "Setup Complete! 🎉"
echo ""
echo -e "  ${GREEN}${BOLD}Your Matrix stack is running on LXC IP: ${LXC_IP}${NC}"
echo ""
echo -e "  ${CYAN}Element Web:${NC}   https://${ELEMENT_DOMAIN}"
echo -e "  ${CYAN}Matrix API:${NC}    https://${MATRIX_DOMAIN}"
echo -e "  ${CYAN}Jitsi Meet:${NC}    https://${JITSI_DOMAIN}  (via Element widget only)"
echo ""
echo -e "  ${YELLOW}${BOLD}Matrix Admin Account:${NC}"
echo -e "    Username: ${ADMIN_USER}"
echo -e "    Password: ${ADMIN_PASS}"
echo ""
echo -e "  ${YELLOW}${BOLD}Required DNS records (→ ${LXC_IP}):${NC}"
echo -e "    A  ${ELEMENT_DOMAIN}"
echo -e "    A  ${MATRIX_DOMAIN}"
echo -e "    A  ${JITSI_DOMAIN}"
echo -e "    SRV _matrix._tcp.${DOMAIN}  10 0 443 ${MATRIX_DOMAIN}"
echo ""
if [[ "$SKIP_SSL" == "true" ]]; then
  warn "Running with self-signed certificates."
  warn "When DNS is ready, run: ./scripts/renew-ssl.sh"
fi
echo -e "  ${BLUE}All credentials saved to:${NC} ${ENV_FILE}"
echo ""
