#!/bin/bash
###############################################################################
# Configure Matrix Synapse
# Final TURN layout:
#   client -> turns:${TURN}:443?transport=tcp
#   nginx stream SNI mux -> 127.0.0.1:5349
#   coturn runs on loopback only
###############################################################################
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "  Configuring Synapse..."

ENV_FILE="/root/matrix.env"
[[ -f "$ENV_FILE" ]] || { echo "Missing $ENV_FILE"; exit 1; }

set -a
. "$ENV_FILE"
set +a

: "${DOMAIN:?Missing DOMAIN in matrix.env}"
: "${TURN:?Missing TURN in matrix.env}"
: "${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD in matrix.env}"
: "${REG_SECRET:?Missing REG_SECRET in matrix.env}"
: "${MACAROON_SECRET:?Missing MACAROON_SECRET in matrix.env}"
: "${FORM_SECRET:?Missing FORM_SECRET in matrix.env}"
: "${TURN_SECRET:?Missing TURN_SECRET in matrix.env}"

SYNAPSE_CONF="/etc/matrix-synapse"
SYNAPSE_DATA="/var/lib/matrix-synapse"

mkdir -p \
  "${SYNAPSE_CONF}" \
  "${SYNAPSE_DATA}/media" \
  /var/log/matrix-synapse \
  /var/run/matrix-synapse

chown -R matrix-synapse:matrix-synapse \
  "${SYNAPSE_DATA}" \
  /var/log/matrix-synapse \
  /var/run/matrix-synapse

###############################################################################
# Signing key
###############################################################################

SIGNING_KEY="${SYNAPSE_CONF}/homeserver.signing.key"

if [[ ! -f "$SIGNING_KEY" ]]; then
  SYNAPSE_PY="/opt/venvs/matrix-synapse/bin/python"
  [[ ! -x "$SYNAPSE_PY" ]] && SYNAPSE_PY="/usr/bin/python3"

  sudo -u matrix-synapse "$SYNAPSE_PY" - <<PYEOF 2>/dev/null || true
from signedjson.key import generate_signing_key, write_signing_keys
key = generate_signing_key("a_1")
with open("${SIGNING_KEY}", "w") as f:
    write_signing_keys(f, [key])
PYEOF

  chown matrix-synapse:matrix-synapse "$SIGNING_KEY" 2>/dev/null || true
  chmod 600 "$SIGNING_KEY" 2>/dev/null || true
fi

###############################################################################
# Read Valkey password
###############################################################################

VALKEY_PASS="${VALKEY_PASS:-}"
if [[ -z "$VALKEY_PASS" && -f /root/matrix.env ]]; then
  VALKEY_PASS="$(grep '^VALKEY_PASS=' /root/matrix.env | cut -d= -f2- || true)"
fi

###############################################################################
# Clean conflicting autogenerated files if needed
###############################################################################

mkdir -p /etc/matrix-synapse/conf.d

cat > /etc/matrix-synapse/conf.d/report_stats.yaml <<EOF
# This file is autogenerated, and will be recreated on upgrade if it is deleted.
# Any changes you make will be preserved.

report_stats: false
EOF

cat > /etc/matrix-synapse/conf.d/server_name.yaml <<EOF
# This file is autogenerated, and will be recreated on upgrade if it is deleted.
# Any changes you make will be preserved.

server_name: ${DOMAIN}
EOF

###############################################################################
# Write homeserver.yaml
###############################################################################

cat > "${SYNAPSE_CONF}/homeserver.yaml" <<EOF
##################################################################
# Synapse Homeserver Configuration
# Generated by setup.sh
##################################################################
server_name: "${DOMAIN}"
public_baseurl: "https://${DOMAIN}/"
serve_server_wellknown: true
pid_file: "/var/run/matrix-synapse.pid"

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse_user
    password: "${POSTGRES_PASSWORD}"
    database: synapse
    host: 127.0.0.1
    port: 5432

media_store_path: "${SYNAPSE_DATA}/media"
max_upload_size: 100M

report_stats: false
trusted_key_servers: []
enable_registration: false
enable_registration_without_verification: false
allow_public_rooms_over_federation: false

registration_shared_secret: "${REG_SECRET}"
macaroon_secret_key: "${MACAROON_SECRET}"
form_secret: "${FORM_SECRET}"
signing_key_path: "${SIGNING_KEY}"

password_config:
  enabled: true
  minimum_length: 10
  require_digit: true
  require_lowercase: true
  require_uppercase: true

turn_uris:
  - "turns:${TURN}:443?transport=tcp"
turn_shared_secret: "${TURN_SECRET}"
turn_user_lifetime: 1h
turn_allow_guests: true
EOF

if [[ -n "$VALKEY_PASS" ]]; then
  cat >> "${SYNAPSE_CONF}/homeserver.yaml" <<EOF

redis:
  enabled: true
  host: 127.0.0.1
  port: 6379
  password: "${VALKEY_PASS}"
EOF
fi

chown matrix-synapse:matrix-synapse "${SYNAPSE_CONF}/homeserver.yaml"
chmod 640 "${SYNAPSE_CONF}/homeserver.yaml"

###############################################################################
# Restart Synapse
###############################################################################

systemctl daemon-reload
systemctl enable matrix-synapse
systemctl restart matrix-synapse

echo "  Waiting for Synapse..."
for i in $(seq 1 30); do
  if curl -fs http://127.0.0.1:8008/_matrix/client/versions >/dev/null 2>&1; then
    echo "  Synapse responding."
    break
  fi
  sleep 2
done

echo "  Synapse configured."
echo "  Expected TURN advertised to clients: turns:${TURN}:443?transport=tcp"
