#!/bin/bash
###############################################################################
# Configure Matrix Synapse — matches proven PVE deployment
###############################################################################
set -euo pipefail
echo "  Configuring Synapse..."

SYNAPSE_CONF="/etc/matrix-synapse"
SYNAPSE_DATA="/var/lib/matrix-synapse"

mkdir -p "${SYNAPSE_CONF}" "${SYNAPSE_DATA}/media" /var/log/matrix-synapse /var/run/matrix-synapse
chown -R matrix-synapse:matrix-synapse "${SYNAPSE_DATA}" /var/log/matrix-synapse /var/run/matrix-synapse

# Signing key
SIGNING_KEY="${SYNAPSE_CONF}/homeserver.signing.key"
if [[ ! -f "$SIGNING_KEY" ]]; then
  SYNAPSE_PY="/opt/venvs/matrix-synapse/bin/python"
  [[ ! -x "$SYNAPSE_PY" ]] && SYNAPSE_PY="/usr/bin/python3"
  sudo -u matrix-synapse "$SYNAPSE_PY" -c "
from signedjson.key import generate_signing_key, write_signing_keys
key = generate_signing_key('a_1')
with open('${SIGNING_KEY}', 'w') as f:
    write_signing_keys(f, [key])
" 2>/dev/null || true
  chown matrix-synapse:matrix-synapse "$SIGNING_KEY" 2>/dev/null || true
  chmod 600 "$SIGNING_KEY" 2>/dev/null || true
fi

# Read Valkey pass if available
VALKEY_PASS="${VALKEY_PASS:-}"
[[ -f /root/matrix.env ]] && VALKEY_PASS=$(grep '^VALKEY_PASS=' /root/matrix.env | cut -d= -f2- || echo "")

# Write homeserver.yaml — matches PVE working config
cat > "${SYNAPSE_CONF}/homeserver.yaml" <<HSEOF
##################################################################
# Synapse Homeserver Configuration
# Generated by setup.sh — matches PVE production config
##################################################################
server_name: "${DOMAIN}"
public_baseurl: "https://${DOMAIN}/"
serve_server_wellknown: true
pid_file: "/var/run/matrix-synapse.pid"

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse_user
    password: "${POSTGRES_PASSWORD}"
    database: synapse
    host: 127.0.0.1
    port: 5432

media_store_path: "${SYNAPSE_DATA}/media"
max_upload_size: 100M

report_stats: false
trusted_key_servers: []
enable_registration: false
enable_registration_without_verification: false
allow_public_rooms_over_federation: false

registration_shared_secret: "${REG_SECRET}"
macaroon_secret_key: "${MACAROON_SECRET}"
form_secret: "${FORM_SECRET}"
signing_key_path: "${SIGNING_KEY}"

password_config:
  enabled: true
  minimum_length: 10
  require_digit: true
  require_lowercase: true
  require_uppercase: true

turn_uris:
  - "turn:${TURN}:3478?transport=udp"
  - "turn:${TURN}:3478?transport=tcp"
  - "turns:${TURN}:5349?transport=tcp"
turn_shared_secret: "${TURN_SECRET}"
turn_user_lifetime: 1h
turn_allow_guests: false
HSEOF

# Add Valkey/Redis if available
if [[ -n "$VALKEY_PASS" ]]; then
  cat >> "${SYNAPSE_CONF}/homeserver.yaml" <<REDIS

redis:
  enabled: true
  host: 127.0.0.1
  port: 6379
  password: "${VALKEY_PASS}"
REDIS
fi

chown matrix-synapse:matrix-synapse "${SYNAPSE_CONF}/homeserver.yaml"
chmod 640 "${SYNAPSE_CONF}/homeserver.yaml"

systemctl daemon-reload
systemctl enable matrix-synapse
systemctl restart matrix-synapse

echo "  Waiting for Synapse..."
for i in $(seq 1 30); do
  curl -fs http://127.0.0.1:8008/_matrix/client/versions >/dev/null 2>&1 && { echo "  Synapse responding."; break; }
  sleep 2
done
echo "  Synapse configured."
