#!/bin/bash
# SETUP PHASE - 03: Configure Matrix Synapse homeserver
set -euo pipefail

SYNAPSE_CONF_DIR="/etc/matrix-synapse"
SYNAPSE_DATA_DIR="/var/lib/matrix-synapse"
SYNAPSE_LOG_DIR="/var/log/matrix-synapse"

echo "  Generating Matrix signing key..."
if [[ ! -f "${SYNAPSE_DATA_DIR}/${DOMAIN}.signing.key" ]]; then
  sudo -u matrix-synapse python3 -c "
from signedjson.key import generate_signing_key, write_signing_keys
key = generate_signing_key('a_RsaO')
with open('${SYNAPSE_DATA_DIR}/${DOMAIN}.signing.key', 'w') as f:
    write_signing_keys(f, [key])
print('  Signing key generated.')
"
  chown matrix-synapse:matrix-synapse "${SYNAPSE_DATA_DIR}/${DOMAIN}.signing.key"
  chmod 600 "${SYNAPSE_DATA_DIR}/${DOMAIN}.signing.key"
else
  echo "  Signing key already exists, keeping it."
fi

echo "  Writing homeserver.yaml..."
cat > "${SYNAPSE_CONF_DIR}/homeserver.yaml" <<EOF
# =============================================================================
# Matrix Synapse homeserver configuration
# Generated by setup.sh on ${SETUP_DATE}
# Domain: ${DOMAIN}
# =============================================================================

server_name: "${DOMAIN}"
public_baseurl: "https://${MATRIX_DOMAIN}/"
pid_file: /var/run/matrix-synapse/homeserver.pid

# ── Listeners ─────────────────────────────────────────────────────────────
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false

  - port: 9000
    tls: false
    type: http
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [metrics, health]

# ── Database (PostgreSQL) ─────────────────────────────────────────────────
database:
  name: psycopg2
  args:
    user: synapse
    password: "${POSTGRES_PASS}"
    database: synapse
    host: 127.0.0.1
    port: 5432
    cp_min: 5
    cp_max: 10

# ── Logging ──────────────────────────────────────────────────────────────
log_config: "${SYNAPSE_CONF_DIR}/log.yaml"

# ── Media ────────────────────────────────────────────────────────────────
media_store_path: "${SYNAPSE_DATA_DIR}/media_store"
max_upload_size: 100M
max_image_pixels: 32M
dynamic_thumbnails: false
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '169.254.0.0/16'
  - '::1/128'
  - 'fe80::/10'
  - 'fc00::/7'

# ── Signing keys ─────────────────────────────────────────────────────────
signing_key_path: "${SYNAPSE_DATA_DIR}/${DOMAIN}.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

# ── Registration ─────────────────────────────────────────────────────────
enable_registration: false
registration_shared_secret: "${MATRIX_SHARED_SECRET}"

# ── Rate limiting ────────────────────────────────────────────────────────
rc_message:
  per_second: 0.2
  burst_count: 10
rc_registration:
  per_second: 0.17
  burst_count: 3
rc_login:
  address:
    per_second: 0.15
    burst_count: 5
  account:
    per_second: 0.18
    burst_count: 4
  failed_attempts:
    per_second: 0.19
    burst_count: 7

# ── TURN/STUN (for Jitsi + VoIP) ────────────────────────────────────────
turn_uris:
  - "turn:${DOMAIN}:3478?transport=udp"
  - "turn:${DOMAIN}:3478?transport=tcp"
  - "turns:${DOMAIN}:5349?transport=tcp"
turn_shared_secret: "${TURN_SECRET}"
turn_user_lifetime: 86400000
turn_allow_guests: true

# ── Redis/Valkey ─────────────────────────────────────────────────────────
redis:
  enabled: true
  host: 127.0.0.1
  port: 6379
  password: "${VALKEY_PASS}"

# ── Federation ───────────────────────────────────────────────────────────
allow_public_rooms_over_federation: false
allow_public_rooms_without_auth: false

# ── Push ─────────────────────────────────────────────────────────────────
push:
  include_content: false

# ── Admin ────────────────────────────────────────────────────────────────
admin_contact: "mailto:admin@${DOMAIN}"
suppress_key_server_warning: true
EOF

chown matrix-synapse:matrix-synapse "${SYNAPSE_CONF_DIR}/homeserver.yaml"
chmod 640 "${SYNAPSE_CONF_DIR}/homeserver.yaml"

echo "  Writing log.yaml..."
cat > "${SYNAPSE_CONF_DIR}/log.yaml" <<EOF
version: 1
formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: ${SYNAPSE_LOG_DIR}/homeserver.log
    when: midnight
    backupCount: 7
    encoding: utf8
  console:
    class: logging.StreamHandler
    formatter: precise
loggers:
    synapse.storage.SQL:
        level: WARNING
root:
    level: WARNING
    handlers: [file, console]
disable_existing_loggers: false
EOF
chown matrix-synapse:matrix-synapse "${SYNAPSE_CONF_DIR}/log.yaml"

echo "  Running Synapse DB migration..."
sudo -u matrix-synapse python3 -m synapse.app.homeserver \
  --config-path "${SYNAPSE_CONF_DIR}/homeserver.yaml" \
  --generate-config \
  --report-stats=no \
  --server-name "${DOMAIN}" 2>/dev/null || true

echo "  Starting Matrix Synapse..."
systemctl enable matrix-synapse
systemctl restart matrix-synapse

echo "  Waiting for Synapse health endpoint..."
for i in $(seq 1 30); do
  curl -sf "http://127.0.0.1:9000/health" &>/dev/null && break
  sleep 2
done

if curl -sf "http://127.0.0.1:9000/health" &>/dev/null; then
  echo "  Synapse is healthy."
else
  echo "  WARNING: Synapse health check not responding yet (may still be starting)"
fi

echo "  Creating Matrix admin user: ${ADMIN_USER}..."
sleep 2
register_new_matrix_user \
  -c "${SYNAPSE_CONF_DIR}/homeserver.yaml" \
  -u "${ADMIN_USER}" \
  -p "${ADMIN_PASS}" \
  -a \
  http://127.0.0.1:8008 2>/dev/null && \
  echo "  Admin user @${ADMIN_USER}:${DOMAIN} created." || \
  echo "  (Admin user may already exist — skipping)"
