#!/bin/bash
# SETUP PHASE - 05: Configure Jitsi Meet (prosody, jicofo, JVB2)
set -euo pipefail

echo "  Setting hostname for Jitsi domain..."
hostnamectl set-hostname "${JITSI_DOMAIN}" 2>/dev/null || echo "${JITSI_DOMAIN}" > /etc/hostname
# Ensure loopback resolves it
if ! grep -q "${JITSI_DOMAIN}" /etc/hosts; then
  echo "127.0.0.1 ${JITSI_DOMAIN}" >> /etc/hosts
fi

# ── Prosody ───────────────────────────────────────────────────────────────────
echo "  Writing prosody configuration..."
PROSODY_VHOST="/etc/prosody/conf.avail/${JITSI_DOMAIN}.cfg.lua"
cat > "${PROSODY_VHOST}" <<EOF
-- Prosody configuration for ${JITSI_DOMAIN}
-- Generated by setup.sh

plugin_paths = { "/usr/share/jitsi-meet/prosody-plugins/" }

-- Virtual host for the Jitsi domain
VirtualHost "${JITSI_DOMAIN}"
    authentication = "jitsi-anonymous"
    c2s_require_encryption = false
    modules_enabled = {
        "bosh";
        "websocket";
        "smacks";
        "pubsub";
        "ping";
        "speakerstats";
        "conference_duration";
        "end_conference";
        "muc_lobby_rooms";
        "muc_breakout_rooms";
        "av_moderation";
        "room_metadata";
        "polls";
    }
    speakerstats_component   = "speakerstats.${JITSI_DOMAIN}"
    conference_duration_component = "conferenceduration.${JITSI_DOMAIN}"
    lobby_muc                = "lobby.${JITSI_DOMAIN}"
    breakout_rooms_muc       = "breakout.${JITSI_DOMAIN}"
    room_metadata_component  = "metadata.${JITSI_DOMAIN}"
    main_muc                 = "conference.${JITSI_DOMAIN}"

-- Conference MUC
Component "conference.${JITSI_DOMAIN}" "muc"
    storage = "memory"
    modules_enabled = {
        "muc_meeting_id";
        "muc_domain_mapper";
        "polls";
        "muc_rate_limit";
        "muc_lobby_rooms";
        "muc_breakout_rooms";
        "av_moderation";
        "room_metadata";
    }
    admins = { "focus@auth.${JITSI_DOMAIN}" }
    muc_room_locking = false
    muc_room_default_public_jids = true

-- Focus (jicofo) component
Component "focus.${JITSI_DOMAIN}"
    component_secret = "${JITSI_PASS}"

-- Video bridge component
Component "jvb.${JITSI_DOMAIN}"
    component_secret = "${JITSI_APP_SECRET}"

-- Internal auth domain (services auth here)
VirtualHost "auth.${JITSI_DOMAIN}"
    authentication = "internal_plain"

-- Lobby rooms
Component "lobby.${JITSI_DOMAIN}" "muc"
    storage = "memory"
    restrict_room_creation = true
    muc_room_locking = false
    muc_room_default_public_jids = true

-- Breakout rooms
Component "breakout.${JITSI_DOMAIN}" "muc"
    storage = "memory"
    restrict_room_creation = true
    muc_room_locking = false
    muc_room_default_public_jids = true

-- Speaker stats component
Component "speakerstats.${JITSI_DOMAIN}" "speakerstats_component"
    muc_component = "conference.${JITSI_DOMAIN}"

-- Conference duration
Component "conferenceduration.${JITSI_DOMAIN}" "conference_duration_component"
    muc_component = "conference.${JITSI_DOMAIN}"

-- AV moderation
Component "avmoderation.${JITSI_DOMAIN}" "av_moderation_component"
    muc_component = "conference.${JITSI_DOMAIN}"

-- Room metadata
Component "metadata.${JITSI_DOMAIN}" "room_metadata_component"
    muc_component = "conference.${JITSI_DOMAIN}"
EOF

ln -sf "${PROSODY_VHOST}" "/etc/prosody/conf.d/${JITSI_DOMAIN}.cfg.lua"

echo "  Starting prosody and creating XMPP users..."
systemctl enable prosody
systemctl restart prosody
sleep 3

prosodyctl --config /etc/prosody/prosody.cfg.lua register \
  focus "auth.${JITSI_DOMAIN}" "${JITSI_PASS}" 2>/dev/null || true
prosodyctl --config /etc/prosody/prosody.cfg.lua register \
  jvb "auth.${JITSI_DOMAIN}" "${JITSI_APP_SECRET}" 2>/dev/null || true

# ── jicofo ────────────────────────────────────────────────────────────────────
echo "  Writing jicofo configuration..."
cat > /etc/jitsi/jicofo/config <<EOF
JICOFO_HOST=${JITSI_DOMAIN}
JICOFO_HOSTNAME=${JITSI_DOMAIN}
JICOFO_SECRET=${JITSI_PASS}
JICOFO_PORT=5347
JICOFO_AUTH_DOMAIN=auth.${JITSI_DOMAIN}
JICOFO_AUTH_USER=focus
JICOFO_AUTH_PASSWORD=${JITSI_PASS}
JAVA_SYS_PROPS="-Dconfig.file=/etc/jitsi/jicofo/jicofo.conf -Djava.util.logging.config.file=/etc/jitsi/jicofo/logging.properties"
EOF

cat > /etc/jitsi/jicofo/jicofo.conf <<EOF
jicofo {
  xmpp {
    service {
      domain = "${JITSI_DOMAIN}"
      xmpp-domain = "${JITSI_DOMAIN}"
    }
    client {
      server = "localhost"
      domain = "auth.${JITSI_DOMAIN}"
      username = "focus"
      password = "${JITSI_PASS}"
    }
  }
  bridge {
    brewery-jid = "JvbBrewery@internal.auth.${JITSI_DOMAIN}"
  }
}
EOF

# ── JVB2 ──────────────────────────────────────────────────────────────────────
echo "  Writing jitsi-videobridge2 configuration..."
cat > /etc/jitsi/videobridge/config <<EOF
JVB_HOSTNAME=${JITSI_DOMAIN}
JVB_HOST=localhost
JVB_PORT=5347
JVB_SECRET=${JITSI_APP_SECRET}
JAVA_SYS_PROPS="-Dconfig.file=/etc/jitsi/videobridge/jvb.conf -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
EOF

cat > /etc/jitsi/videobridge/jvb.conf <<EOF
videobridge {
  ice {
    udp {
      port = 10000
    }
    tcp {
      enabled = true
      port = 4443
    }
  }
  apis {
    xmpp-client {
      configs {
        xmpp-server-1 {
          hostname = "localhost"
          domain = "auth.${JITSI_DOMAIN}"
          username = "jvb"
          password = "${JITSI_APP_SECRET}"
          muc_jids = "JvbBrewery@internal.auth.${JITSI_DOMAIN}"
          muc_nickname = "jvb-1"
          disable_certificate_verification = true
        }
      }
    }
  }
  stats {
    enabled = true
  }
  websockets {
    enabled = true
    domain = "${JITSI_DOMAIN}"
    tls = true
    server-id = "jvb-1"
  }
}
EOF

# ── Jitsi Meet config.js ─────────────────────────────────────────────────────
echo "  Writing Jitsi Meet config.js..."
cat > /usr/share/jitsi-meet/config.js <<EOF
/* Jitsi Meet config - generated by setup.sh */
var config = {
    hosts: {
        domain: '${JITSI_DOMAIN}',
        muc: 'conference.${JITSI_DOMAIN}',
        focus: 'focus.${JITSI_DOMAIN}',
    },
    bosh: 'https://${JITSI_DOMAIN}/http-bind',
    websocket: 'wss://${JITSI_DOMAIN}/xmpp-websocket',
    clientNode: 'https://jitsi.org/jitsimeet',
    enableWelcomePage: false,
    enableClosePage: false,
    prejoinPageEnabled: true,
    disableDeepLinking: true,
    startWithAudioMuted: false,
    startWithVideoMuted: false,
    enableNoisyMicDetection: true,
    disableAudioLevels: false,
    enableLayerSuspension: true,
    channelLastN: -1,
    p2p: {
        enabled: true,
        stunServers: [
            { urls: 'turn:${DOMAIN}:3478?transport=udp', username: 'jitsi', credential: '${TURN_SECRET}' },
            { urls: 'turns:${DOMAIN}:5349?transport=tcp', username: 'jitsi', credential: '${TURN_SECRET}' },
        ],
    },
    analytics: {},
};
EOF

echo "  Starting jicofo and jitsi-videobridge2..."
systemctl enable jicofo jitsi-videobridge2
systemctl restart jicofo jitsi-videobridge2

echo "  Jitsi Meet configured."
