#!/bin/bash
# SETUP PHASE - 06: Configure coturn TURN/STUN server
set -euo pipefail

echo "  Writing coturn configuration..."
cat > /etc/turnserver.conf <<EOF
# coturn configuration - generated by setup.sh
# TURN/STUN for Matrix Synapse + Jitsi WebRTC

# Ports
listening-port=3478
tls-listening-port=5349

# Bind to LXC IP
listening-ip=${LXC_IP}
relay-ip=${LXC_IP}

# If behind NAT/router, uncomment and set:
# external-ip=<YOUR_PUBLIC_IP>/${LXC_IP}

# Authentication - time-limited HMAC tokens (no static users)
lt-cred-mech
use-auth-secret
static-auth-secret=${TURN_SECRET}
realm=${DOMAIN}

# Logging
log-file=/var/log/coturn/turn.log
syslog

# Security - deny access to internal networks
no-loopback-peers
no-multicast-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

# TLS (populated by ssl setup step if Let's Encrypt succeeds)
# cert=/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
# pkey=/etc/letsencrypt/live/${DOMAIN}/privkey.pem

# Relay UDP ports (WebRTC media)
min-port=49152
max-port=65535

# Disable plain TCP relay (TURN-over-TCP only for signaling)
no-tcp-relay

# Required for WebRTC
fingerprint

# CLI diagnostics (localhost only)
cli-ip=127.0.0.1
cli-port=5766
cli-password=${TURN_SECRET}
EOF

echo "  Starting coturn..."
systemctl enable coturn
systemctl restart coturn

sleep 2
if ss -ulnp 2>/dev/null | grep -q ':3478'; then
  echo "  coturn listening on UDP 3478."
else
  echo "  WARNING: coturn may not be listening - check: journalctl -u coturn"
fi
